// Generated by CoffeeScript 1.3.3
(function() {
  var Collection, mixin, operators, sort,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  operators = {
    eq: function(l, r) {
      return l === r;
    },
    gt: function(l, r) {
      return l > r;
    },
    gte: function(l, r) {
      return l >= r;
    },
    lt: function(l, r) {
      return l < r;
    },
    lte: function(l, r) {
      return l <= r;
    },
    not: function(l, r) {
      return l !== r;
    },
    match: function(l, r) {
      return r.test(l);
    },
    byLength: function(l, r) {
      return l.length === r;
    },
    within: function(l, arr) {
      return __indexOf.call(arr, l) >= 0;
    },
    between: function(l, arr) {
      var vl, vr;
      vl = arr[0];
      vr = arr[1] || vl;
      return l >= vl && l <= vr;
    }
  };

  sort = function(collection, conditions) {
    var limit, order, orderBy;
    if (!(conditions && conditions.orderBy)) {
      return collection;
    }
    orderBy = conditions.orderBy, order = conditions.order, limit = conditions.limit;
    collection = _.sortBy(collection, function(model) {
      return model[orderBy];
    });
    if (order && order.toLowerCase() === 'desc') {
      collection = collection.reverse();
    }
    if (limit) {
      collection = collection.slice(0, limit);
    }
    return collection;
  };

  mixin = {};

  _.each(operators, function(compare, method) {
    return mixin[method] = function(collection, conditions, sortingOptions) {
      var res;
      res = _.filter(collection, function(item) {
        return _.all(conditions, function(val, key) {
          return compare(item[key], val);
        });
      });
      return sort(res, sortingOptions);
    };
  });

  mixin.query = function(collection, options, sortingOptions) {
    var res;
    res = _.filter(collection, function(model) {
      return _.all(options, function(conditions, method) {
        var compare;
        compare = operators[method];
        return _.all(conditions, function(val, key) {
          return compare(model[key], val);
        });
      });
    });
    return sort(res, sortingOptions);
  };

  _.mixin(mixin);

  Collection = (function(_super) {
    var _this = this;

    __extends(Collection, _super);

    function Collection() {
      return Collection.__super__.constructor.apply(this, arguments);
    }

    _.each(operators, function(compare, method) {
      return Collection.prototype[method] = function(conditions, sortingOptions) {
        return _[method](this.toJSON(), conditions, sortingOptions);
      };
    });

    Collection.prototype.query = function(conditions, sortingOptions) {
      return _.query(this.toJSON(), conditions, sortingOptions);
    };

    return Collection;

  }).call(this, Backbone.Collection);

  if (typeof require !== "undefined" && require !== null) {
    module.exports = Collection;
  } else {
    window.Collection = Collection;
  }

}).call(this);
