// Generated by CoffeeScript 1.3.3
(function() {
  var data, el;

  data = [
    {
      age: 29,
      duration: 196,
      scores: [890, 402, 240],
      difficulty: "easy",
      male: true,
      name: "wade"
    }, {
      age: 54,
      duration: 47,
      scores: [919, 149, 1017],
      difficulty: "easy",
      male: false,
      name: "celina"
    }, {
      age: 73,
      duration: 111,
      scores: [401, 698],
      difficulty: "hard",
      male: true,
      name: "freddie"
    }, {
      age: 35,
      duration: 53,
      scores: [419, 1030],
      difficulty: "hard",
      male: false,
      name: "terra"
    }, {
      age: 36,
      duration: 208,
      scores: [619, 66, 968],
      difficulty: "impossible",
      male: true,
      name: "enrique"
    }, {
      age: 12,
      duration: 127,
      scores: [486, 680, 555],
      difficulty: "impossible",
      male: true,
      name: "terrence"
    }, {
      age: 23,
      duration: 148,
      scores: [111, 255, 1014, 368],
      difficulty: "hard",
      male: false,
      name: "herminia"
    }, {
      age: 12,
      duration: 54,
      scores: [134, 297, 706],
      difficulty: "easy",
      male: true,
      name: "eduardo"
    }, {
      age: 64,
      duration: 101,
      scores: [1011, 488, 881],
      difficulty: "easy",
      male: false,
      name: "isabella"
    }, {
      age: 16,
      duration: 166,
      scores: [661, 413],
      difficulty: "impossible",
      male: false,
      name: "robert"
    }, {
      age: 32,
      duration: 236,
      scores: [962, 975, 548],
      difficulty: "noob",
      male: false,
      name: "beverley"
    }, {
      age: 62,
      duration: 186,
      scores: [347, 878, 59],
      difficulty: "hard",
      male: false,
      name: "lesa"
    }, {
      age: 16,
      duration: 153,
      scores: [917, 975, 157],
      difficulty: "impossible",
      male: true,
      name: "rene"
    }, {
      age: 71,
      duration: 221,
      scores: [123, 805, 768, 455],
      difficulty: "hard",
      male: false,
      name: "sharlene"
    }, {
      age: 75,
      duration: 167,
      scores: [631, 319, 972, 762],
      difficulty: "impossible",
      male: true,
      name: "terrance"
    }, {
      age: 19,
      duration: 215,
      scores: [562, 179, 316],
      difficulty: "hard",
      male: true,
      name: "kent"
    }, {
      age: 41,
      duration: 82,
      scores: [332, 164, 216],
      difficulty: "impossible",
      male: false,
      name: "felecia"
    }, {
      age: 78,
      duration: 126,
      scores: [439, 808, 308],
      difficulty: "easy",
      male: true,
      name: "seth"
    }, {
      age: 56,
      duration: 63,
      scores: [291, 427],
      difficulty: "noob",
      male: false,
      name: "leta"
    }, {
      age: 5,
      duration: 146,
      scores: [107, 262, 385],
      difficulty: "hard",
      male: true,
      name: "tracy"
    }, {
      age: 15,
      duration: 138,
      scores: [789, 1004, 654, 846],
      difficulty: "noob",
      male: true,
      name: "marion"
    }, {
      age: 53,
      duration: 108,
      scores: [195, 317],
      difficulty: "impossible",
      male: false,
      name: "louella"
    }, {
      age: 55,
      duration: 223,
      scores: [285, 466, 218, 738],
      difficulty: "easy",
      male: false,
      name: "brandie"
    }, {
      age: 41,
      duration: 230,
      scores: [618, 227],
      difficulty: "impossible",
      male: true,
      name: "sergio"
    }, {
      age: 62,
      duration: 229,
      scores: [212, 553, 181],
      difficulty: "easy",
      male: true,
      name: "kirk"
    }, {
      age: 41,
      duration: 132,
      scores: [724, 167, 93, 666],
      difficulty: "noob",
      male: true,
      name: "perry"
    }, {
      age: 35,
      duration: 223,
      scores: [146, 434, 788, 477],
      difficulty: "impossible",
      male: true,
      name: "salvador"
    }, {
      age: 23,
      duration: 153,
      scores: [665, 527, 943, 100],
      difficulty: "easy",
      male: false,
      name: "deann"
    }, {
      age: 59,
      duration: 65,
      scores: [682, 677, 198],
      difficulty: "noob",
      male: true,
      name: "marshall"
    }, {
      age: 47,
      duration: 159,
      scores: [455, 249, 648],
      difficulty: "noob",
      male: true,
      name: "andy"
    }, {
      age: 29,
      duration: 130,
      scores: [707, 111],
      difficulty: "hard",
      male: true,
      name: "virgil"
    }, {
      age: 84,
      duration: 210,
      scores: [88, 569, 282],
      difficulty: "noob",
      male: false,
      name: "kitty"
    }, {
      age: 25,
      duration: 145,
      scores: [107, 649],
      difficulty: "easy",
      male: false,
      name: "letitia"
    }, {
      age: 9,
      duration: 187,
      scores: [442, 634, 736, 863],
      difficulty: "impossible",
      male: true,
      name: "ross"
    }, {
      age: 50,
      duration: 99,
      scores: [183, 555],
      difficulty: "hard",
      male: true,
      name: "daryl"
    }, {
      age: 68,
      duration: 212,
      scores: [200, 206, 899],
      difficulty: "easy",
      male: false,
      name: "noelle"
    }, {
      age: 64,
      duration: 146,
      scores: [104, 703, 199],
      difficulty: "noob",
      male: true,
      name: "willard"
    }, {
      age: 11,
      duration: 162,
      scores: [797, 1028, 605],
      difficulty: "hard",
      male: false,
      name: "elba"
    }, {
      age: 53,
      duration: 167,
      scores: [664, 824, 693],
      difficulty: "hard",
      male: false,
      name: "pansy"
    }, {
      age: 61,
      duration: 75,
      scores: [847, 990, 90, 356],
      difficulty: "hard",
      male: false,
      name: "vonda"
    }
  ];

  el = function(tag) {
    tag || (tag = 'div');
    return $(document.createElement(tag));
  };

  $(function() {
    var $target, addTable, byLength, high, kids, makeRow, mixed, nameAlike, noobish, pros, users;
    $target = $('#demo');
    makeRow = function(data, tag) {
      var $row;
      $row = el('tr');
      _.each(data, function(val, key) {
        var $cell;
        return $cell = el(tag).text(val).appendTo($row);
      });
      return $row;
    };
    addTable = function(data, codesample) {
      var $code, $pre, $table, columns, row, _i, _len;
      if (codesample == null) {
        codesample = '';
      }
      $table = el('table');
      columns = _.keys(data[0]);
      $table.append(makeRow(columns, 'th'));
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        row = data[_i];
        $table.append(makeRow(row, 'td'));
      }
      $code = el('code').text(codesample);
      $pre = el('pre').append($code);
      $target.append($pre);
      return $target.append($table);
    };
    data = _.map(data, function(row) {
      row.highscore = _.max(row.scores);
      delete row.scores;
      return row;
    });
    users = new Collection(data);
    nameAlike = users.match({
      name: /in/g
    });
    addTable(nameAlike, "users.match name: /in/g");
    byLength = users.byLength({
      name: 5
    });
    addTable(byLength, "users.byLength name: 5");
    pros = users.within({
      difficulty: ['hard', 'impossible']
    }, {
      orderBy: 'age',
      order: 'asc',
      limit: 5
    });
    addTable(pros, "users.within { difficulty: ['hard', 'impossible'] }, { orderBy: 'age', order: 'asc', limit: 5 }");
    high = users.gt({
      highscore: 1000
    }, {
      orderBy: 'highscore',
      order: 'desc'
    });
    addTable(high, "high = users.gt highscore: 1000");
    kids = users.between({
      age: [5, 12]
    });
    addTable(kids, "users.between age: [5, 12]");
    noobish = users.query({
      eq: {
        difficulty: 'noob'
      },
      lt: {
        highscore: 600
      }
    }, {
      orderBy: 'name',
      order: 'desc'
    });
    addTable(noobish, "users.query { eq: { difficulty: 'noob' }, lt: { highscore: 600 } }, { orderBy: 'name', order: 'desc' }");
    mixed = users.query({
      gte: {
        highscore: 150
      },
      gt: {
        duration: 200
      },
      between: {
        age: [5, 35]
      },
      eq: {
        male: true
      }
    });
    return addTable(mixed, "users.query {\n    gte:\n        highscore: 150\n    gt:\n        duration: 200\n    between:\n        age: [5, 35]\n    eq:\n        male: yes\n}");
  });

}).call(this);
